### ISSUE TITLE
Allow specifying `--context`

### ISSUE THREAD

**Issue by onedr0p** [clbx/kubectl-browse-pvc#14]
My `KUBECONFIG` is exported like this:

```
export KUBECONFIG="kubernetes/main/kubeconfig:kubernetes/storage/kubeconfig"
```

This works great with kubectl e.g. `kubectl --context main get po` but does not work with `kubectl-browse-pvc`

```sh
✖ k browse-pvc --namespace default volsync-zwave-js-ui-r2-cache
panic: stat /Users/devin/Code/repos/onedr0p/home-ops/kubernetes/main/kubeconfig:/Users/devin/Code/repos/onedr0p/home-ops/kubernetes/storage/kubeconfig: no such file or directory

goroutine 1 [running]:
main.getClientSetFromKubeconfig()
	/Users/runner/work/kubectl-browse-pvc/kubectl-browse-pvc/util.go:93 +0x165
main.getCommand(0xc00041a2c0)
	/Users/runner/work/kubectl-browse-pvc/kubectl-browse-pvc/main.go:64 +0x94
github.com/urfave/cli/v2.(*Command).Run(0xc0003e0840, 0xc00041a2c0, {0xc00012e120, 0x6, 0x6})
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc000146780, {0x252cbb0?, 0xc00011c010}, {0xc00012e120, 0x6, 0x6})
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
	/Users/runner/work/kubectl-browse-pvc/kubectl-browse-pvc/main.go:51 +0x2dc
```

and with trying to add `--context`

```
✖ k browse-pvc --context main --namespace default volsync-zwave-js-ui-r2-cache
Incorrect Usage: flag provided but not defined: -context

NAME:
   kubectl browse-pvc - Kubernetes PVC Browser

USAGE:
   kubectl browse-pvc [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --namespace value, -n value  Specify namespace of  (default: "default")
   --image value, -i value      Image to mount job to (default: "clbx/pvcb-edit")
   --help, -h                   show help
2024/02/15 11:03:55 flag provided but not defined: -context
```

**Comment by clbx** [comment]
This should be fixed in the newest release.

**Comment by onedr0p** [comment]
Thank you so much, works wonderfully <3
